# refs. https://github.com/bmvantunes/youtube-2020-august-github-pages-github-actions
name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Packages
        run: npm ci

      - name: Build 🔧
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /gitgitWi.github.io
      - run: npm run export
        env:
          NEXT_PUBLIC_BASE_PATH: /gitgitWi.github.io
      - run: touch ./out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: out
